### ISSUE TITLE
`es2015` preset is used despite not beeing listed as a dependency

### ISSUE THREAD

**Issue by flxbe** [alex-saunders/npm-ui#11]
## Bug or Feature?
Bug

## Current Situation
In `package.json`, `babel-preset-env` is listed as a dependency, but `es2015` is used in `.babelrc`.

## Intended Change
Update `.babelrc` to use the new `env` preset.

## To complete this, the following needs to be done

* [x] Update `.babelrc`

**Comment by alex-saunders** [comment]
@flxbe cheers for this, fixed by #12
