### ISSUE TITLE
Clean up styles

### ISSUE THREAD

**Issue by alex-saunders** [alex-saunders/npm-ui#5]
## Bug or Feature?
Bug

## Current Situation

Current styles are quite all over the place and a lot of hacky overrides of the styles provided by the rmwc components.

## Intended Change

Would be good to have much more structured styling. Would need to discuss what approach would be best to approach, e.g. styled components, css variables, sass etc.

**Comment by CVarisco** [comment]
What do you think to use CSS Modules on the project? 
With the new folder structure should be easy to use it 🙂

**Comment by alex-saunders** [comment]
@CVarisco I actually intended to use CSS Modules initially but it was proving tricky to get it working with the rmcw library. If you're able to get it hooked up and compatible with the material components library then i'm happy to get it merged

**Comment by CVarisco** [comment]
Hi @alex-saunders,

I'm working on my branch to integrate CSSModules.

In the next days, I'll do a PR with the integration, but we should fix the styles because the styles code now are only global and only you for now know what is a overwrite of material-components.

I already integrate CSS Modules on the project as you can see here

![test](https://user-images.githubusercontent.com/7335613/34652591-c68cfaee-f3e0-11e7-9306-8c77db4c5c7a.gif)

If you want a preview you can see [here](https://github.com/CVarisco/npm-ui/tree/5-Integrate-CSSModules) 🎉

**Comment by alex-saunders** [comment]
Perfect, it's looking good already. I'll be impressed if you can get it working with the material-components ;) 

Generally all class names that start with `.mdc` are overrides of the material-components default styles.

We should definitely figure out a best approach for overriding these styles before merging though as at the moment a lot of it is hacky (overriding css variables at class level because our `theme.scss` doesn't match up to mdc's theme style for example).

Would be good to hear your thoughts on this.

**Comment by CVarisco** [comment]
Hi @alex-saunders !

I created a PR where everything works well (also the UI is ok now).

> We should definitely figure out a best approach for overriding these styles before merging though as at the moment a lot of it is hacky (overriding css variables at class level because our theme.scss doesn't match up to mdc's theme style for example).

I created a `global` scoped in a new file named `theme.scss` that contains the overriding of the theme.

I hope that for you is ok 👍 
I'm here for every question that you can have 🙂

**Comment by alex-saunders** [comment]
Hi @CVarisco 

Thanks for your work on this!

We'll keep the conversation going in the thread for #15 if that's ok?

**Comment by CVarisco** [comment]
Sure man!

**Comment by alex-saunders** [comment]
#15 fixes this issue 

Though we will probably reopen in future for when styles are looked at again
